# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'versioninfo(); Pkg.clone(pwd()); Pkg.build("Identity"); Pkg.test("Identity"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Identity"));Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
